### ISSUE TITLE
Namespace 'mobileraker' not found

### ISSUE THREAD

**Issue by msesterhenn** [Clon1998/mobileraker#119]
Hey there,

I'm trying to connect from my iPhone using mobileraker to my Klipper Instance, installed using MainsailOS.

The App errors out (no specific message) while trying to connect and I found the following in the Moonraker log:

```
2023-02-17 17:26:51,037 [websockets.py:build_error()] - JSON-RPC Request Error: -32601
Namespace 'mobileraker' not found
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/websockets.py", line 300, in execute_method
    result = await callback(params)
  File "/home/pi/moonraker/moonraker/websockets.py", line 414, in func
    result = await callback(
  File "/home/pi/moonraker/moonraker/components/database.py", line 765, in _handle_item_request
    val = await self.get_item(namespace, key)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pi/moonraker/moonraker/components/database.py", line 199, in func_wrapper
    return command_func(*args)
  File "/home/pi/moonraker/moonraker/components/database.py", line 362, in _get_impl
    ns = self._get_record(namespace, key_list[0])
  File "/home/pi/moonraker/moonraker/components/database.py", line 671, in _get_record
    db = self._get_db(namespace)
  File "/home/pi/moonraker/moonraker/components/database.py", line 646, in _get_db
    raise self.server.error(f"Namespace '{namespace}' not found", 404)
utils.ServerError: Namespace 'mobileraker' not found
```

Due to missing support for TMC2240 I have to use BTTs fork of klipper:
https://github.com/bigtreetech/klipper/tree/tmc2240

Could this be broken because the BTT fork is a bit too old?

When trying to use the upstream klipper it gives me at least a better message (that the TMC2240 isn't supported), not sure if it would fail with the same error message as above if I would use another TMC driver for my extruder.

Thanks in advance for your help!

**Comment by msesterhenn** [comment]
After upgrading to latest klipper, the issue disappeared. Looks like there was some incompatibility between the klipper version in the fork of BTT and Mobileraker.

**Comment by Clon1998** [comment]
> After upgrading to latest klipper, the issue disappeared. Looks like there was some incompatibility between the klipper version in the fork of BTT and Mobileraker.

Awesome,
It might have been that there is an issue with the led config parsing in older Klipper Version.
