### ISSUE TITLE
[fan_generic] used as part cooling crashes dashboard, but can't update the app on an older phone

### ISSUE THREAD

**Issue by Bimbovadasz** [Clon1998/mobileraker#171]
Thank you for this great app, I have been really enjoying it!
 
**Describe the bug**
I have the same problem as mentioned in issue #158. I changed the part cooling fan from a [fan] to a [fan_generic], and the dashboard crashes. I know it has been recently fixed in 2.3.0, but unfortunately I am still using my trusty old iPhone 6s, which doesn't get iOS 16 updates. The latest Mobileraker requires iOS 16.4 or later, but I am on 15.7.6.  So I can't update to fix this bug.
Is there a way for me to still use the app with my configs or is it time to get a new phone? :D 

Thank you for the help!

**Smartphone:**
 - Device: iPhone 6s
 - OS: iOS 15.7.6

**Mobileraker-Version: 2.2.5

**Comment by Clon1998** [comment]
Mhhh,
I will Double check the version requirement for IOS.
I increased it for some reason but I don't really remember why.

**Comment by Clon1998** [comment]
> Okay, thank you!

Hey, I reverted the version change and didn't find any good reason to why I increased it. 
The next release will be available for all iOS versions greater or equal to iOS13.0.

**Comment by Bimbovadasz** [comment]
Hey, that's great! 
Thank you!

**Comment by alexvnesta** [comment]
Hi @Clon1998 Thanks for your work on this app. This issue also affects the Creality K1 because it does not have a default [fan] definition. If you have a minute to push the app update to iOS devices, that would be greatly appreciated!

Thanks,
Alex

Details:
Iphone 13 pro, iOS 16.3.1, Creality k1, Fluidd, 

Exception:
 MobilerakerException{Missing field: printFan, parentException: null, parentStack: null}

#0      PrinterBuilder.build (package:mobileraker/data/dto/machine/printer.dart:67)
#1      PrinterService.refreshPrinter (package:mobileraker/service/moonraker/printer_service.dart:204)
<asynchronous suspension>

printer.cfg:

```
# K1
# Printer_size: 220x220x250
# Version: v1.0.2
# CreateDate: 2023/03/21
# Nozzle_mcu: chip: GD32F303CBT6
#             version: CR-K1-MAX-NOZZLE-V1.0.0
# Leveling_mcu: chip: GD32E230F8P6
#             version: CR-K1-MAX-LEVELING-V1.0.0
# mcu: chip: GD32F303RET6
#      version: CR4CU220812S12

[include sensorless.cfg]
[include gcode_macro.cfg]
[include printer_params.cfg]

[mcu]
serial: /dev/ttyS7
baud: 230400
restart_method: command

[mcu nozzle_mcu]
serial: /dev/ttyS1
baud: 230400
restart_method: command

[mcu leveling_mcu]
serial: /dev/ttyS9
baud: 230400
restart_method: command

[verify_heater extruder]
[verify_heater heater_bed]
check_gain_time: 120
heating_gain: 1.0
hysteresis: 10

[mcu rpi]
serial: /tmp/klipper_host_mcu

[bl24c16f]
i2c_mcu: rpi
i2c_bus: i2c.2
i2c_speed: 400000

[idle_timeout]
timeout: 99999999

[virtual_sdcard]
path: /usr/data/printer_data/gcodes

[gcode_arcs]
resolution: 1.0

[temperature_sensor mcu_temp]
sensor_type: temperature_mcu
min_temp: 0
max_temp: 100

[temperature_sensor chamber_temp]
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PC5
min_temp: 0
max_temp: 125

[stepper_x]
step_pin: PC2
dir_pin: !PB9
enable_pin: !PC3
microsteps: 32
rotation_distance: 72
endstop_pin: tmc2209_stepper_x:virtual_endstop
position_endstop: 229
position_min: -5
position_max: 229
homing_speed: 36
homing_retract_dist:0

[tmc2209 stepper_x]
uart_pin:PA9
interpolate: True
run_current:1.5
hold_current:1.0
sense_resistor: 0.100
stealthchop_threshold: 0
uart_address:3
diag_pin: ^PB12
# driver_IHOLDDELAY: 8
# driver_TPOWERDOWN: 20
# driver_TBL: 1
# driver_TOFF: 1
# driver_HEND: 0
# driver_HSTRT: 7
driver_SGTHRS: 65

[stepper_y]
step_pin: PB8
dir_pin: !PB7
enable_pin: !PC3
microsteps: 32
rotation_distance: 72
endstop_pin: tmc2209_stepper_y:virtual_endstop
position_endstop: -0.5
position_min: -0.5
position_max: 226
homing_speed: 36
homing_retract_dist:0

[tmc2209 stepper_y]
uart_pin:PA10
interpolate: True
run_current:1.5
hold_current:1.0
sense_resistor: 0.100
stealthchop_threshold: 0
uart_address:3
diag_pin: ^PB13
# driver_IHOLDDELAY: 8
# driver_TPOWERDOWN: 20
# driver_TBL: 1
# driver_TOFF: 1
# driver_HEND: 0
# driver_HSTRT: 7
driver_SGTHRS: 65

[stepper_z]
step_pin: PB6
dir_pin: !PB5
enable_pin: !PC3
microsteps: 16
rotation_distance:8
gear_ratio: 64:20
endstop_pin: tmc2209_stepper_z:virtual_endstop# PA15   #probe:z_virtual_endstop
position_endstop: 0
position_max: 255
position_min: -5

[tmc2209 stepper_z]
uart_pin: PA11
uart_address: 3
run_current: 0.8
diag_pin: ^PB14
stealthchop_threshold: 0
sense_resistor: 0.100
# driver_IHOLDDELAY: 8
# driver_TPOWERDOWN: 20
# driver_TBL: 1
# driver_TOFF: 1
# driver_HEND: 2
# driver_HSTRT: 2
driver_SGTHRS: 0

[extruder]
max_extrude_only_distance: 1000.0
max_extrude_cross_section: 80
step_pin: nozzle_mcu:PB1
dir_pin: nozzle_mcu:PB0
enable_pin: !nozzle_mcu:PB2
microsteps: 16
rotation_distance: 6.9
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: nozzle_mcu:PB7
sensor_type: EPCOS 100K B57560G104F
sensor_pin: nozzle_mcu:PA0
pressure_advance: 0.04
pressure_advance_smooth_time: 0.040
control: pid
pid_Kp: 25.013
pid_Ki: 2.566
pid_Kd: 60.966
min_temp: 0
max_temp: 320

[tmc2209 extruder]
uart_pin: nozzle_mcu:PB11
tx_pin: nozzle_mcu:PB10
uart_address: 3
run_current: 0.5
sense_resistor: 0.150
stealthchop_threshold: 0
# driver_IHOLDDELAY: 8
# driver_TPOWERDOWN: 20
# driver_TBL: 2
# driver_TOFF: 3
# driver_HEND: 0
# driver_HSTRT: 5

[heater_bed]
heater_pin: PB10
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PC4
control: watermark
# control: pid
# pid_kp: 27
# pid_ki: 0.08
# pid_kd: 0
min_temp: 0
max_temp: 120

[filament_switch_sensor filament_sensor]
pause_on_runout: true
switch_pin: ^!PC15

[multi_pin heater_fans]
pins:nozzle_mcu:PB5,PB2

[heater_fan hotend_fan]
pin: multi_pin:heater_fans
heater: extruder
heater_temp: 40

[static_digital_output my_fan_output_pins]
pins: nozzle_mcu: PB6

[output_pin fan0]
pin: !nozzle_mcu: PB8
pwm: True
cycle_time: 0.0100
hardware_pwm: false
value: 0.00
scale: 255
shutdown_value: 0.0

[output_pin fan1]
pin: PC0
pwm: True
cycle_time: 0.0100
hardware_pwm: false
value: 0.00
scale: 255
shutdown_value: 0.0

[output_pin fan2]
pin: PB1
pwm: True
cycle_time: 0.0100
hardware_pwm: false
value: 0.00
scale: 255
shutdown_value: 0.0

[output_pin LED]
pin:PB0
pwm: True
cycle_time: 0.010
value: 1

[adxl345]
cs_pin: nozzle_mcu:PA4
spi_speed: 5000000
axes_map: x,-z,y
spi_software_sclk_pin: nozzle_mcu:PA5
spi_software_mosi_pin: nozzle_mcu:PA7
spi_software_miso_pin: nozzle_mcu:PA6

[resonance_tester]
accel_chip: adxl345
accel_per_hz: 50
probe_points:
   110,110,10

[hx711s]
count: 4
use_mcu: leveling_mcu
sensor0_clk_pin: leveling_mcu:PA5
sensor1_clk_pin: leveling_mcu:PA2
sensor2_clk_pin: leveling_mcu:PA6
sensor3_clk_pin: leveling_mcu:PA7
sensor0_sdo_pin: leveling_mcu:PA1
sensor1_sdo_pin: leveling_mcu:PA0
sensor2_sdo_pin: leveling_mcu:PA3
sensor3_sdo_pin: leveling_mcu:PA4

[prtouch]
z_offset: 0
base_count: 40
pi_count: 32
min_hold: 2000
max_hold: 6000
s_hot_min_temp: 140
s_hot_max_temp: 200
s_bed_max_temp: 60
pa_fil_len_mm: 5
pa_fil_dis_mm: 30
pa_clr_dis_mm: 30
bed_max_err: 2
max_dis_bef_g28: 0
dead_zone_bef_g28: 0
g28_sta0_speed: 5
g28_sta1_speed: 2.5
g29_rdy_speed: 3
g29_speed: 2.5
show_msg: false
g28_wait_cool_down: true
need_measure_gap: true
pa_clr_down_mm: -0.15
clr_noz_start_x: 95
clr_noz_start_y: 221
clr_noz_len_x: 40
clr_noz_len_y: 2
fix_z_offset:0.06
z_gap_00:0.03
z_gap_01:0.03
z_gap_10:-0.03
z_gap_11:-0.03

[filter]
hft_hz: 1
lft_k1: 0.95
lft_k1_oft: 0.95
lft_k1_cal: 0.95

[dirzctl]
use_mcu: mcu
step_base: 2

[bed_mesh]
speed: 150
mesh_min: 5,5
mesh_max: 215,215
probe_count: 5,5
fade_start: 3.0
fade_end: 10.0

[display_status]

[printer]
kinematics: corexy
max_velocity: 1000
max_accel: 20000
max_accel_to_decel: 10000
max_z_velocity: 20
square_corner_velocity: 5.0
max_z_accel: 300

[pause_resume]

#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#
#*# [input_shaper]
#*# shaper_type_x = ei
#*# shaper_freq_x = 29.0
#*# shaper_type_y = ei
#*# shaper_freq_y = 72.4
#*#
#*# [prtouch default]
#*# z_gap_00 = 0.03
#*# z_gap_01 = 0.03
#*# z_gap_11 = -0.03
#*# z_gap_10 = -0.03
#*#
#*# [bed_mesh default]
#*# version = 1
#*# points =
#*# 	  0.492556, 0.366608, 0.245200, 0.088656, -0.039559
#*# 	  0.348887, 0.241927, 0.133835, 0.029147, -0.117486
#*# 	  0.247191, 0.185265, 0.074629, -0.042819, -0.127397
#*# 	  0.162457, 0.130865, 0.042596, -0.057000, -0.074956
#*# 	  0.179745, 0.135414, 0.094479, 0.060332, 0.014897
#*# x_count = 5
#*# y_count = 5
#*# mesh_x_pps = 2
#*# mesh_y_pps = 2
#*# algo = lagrange
#*# tension = 0.2
#*# min_x = 5.0
#*# max_x = 215.0
#*# min_y = 5.0
#*# max_y = 215.0
```

**Comment by Clon1998** [comment]
Hey @alexvnesta, 
I initially wanted to push the new release this week. However, I discovered a bug that renders the app useless after a print finished due to a change in moonraker's API.

If you guys want you can still join the TestFlight version that makes the app available for Ios 13+ again but contains the bug.

https://testflight.apple.com/join/h9JwuyR0
