### ISSUE TITLE
Dashboard Error - Unable to Fetch Printer

### ISSUE THREAD

**Issue by davidebrock** [Clon1998/mobileraker#177]
The error code I am recieving is: 

**Exception:
 MobilerakerException{Missing field: displayStatus, parentException: null, parentStack: null}

#0      PrinterBuilder.build (package:mobileraker/data/dto/machine/printer.dart:74)
#1      PrinterService.refreshPrinter (package:mobileraker/service/moonraker/printer_service.dart:204)
<asynchronous suspension>**

**Describe the bug**
When I select "Dashboard", nothing loads, and I receive an error in the app that reads, "Error while trying to fetch printer...Please provide the error to the project owner via GitHub!"

**To Reproduce**
1. Go to 'Dashboard'

**Expected behavior**
A visualization of the dashboard

**Screenshots**
![Screenshot 2023-06-14 at 6 07 48 PM](https://github.com/Clon1998/mobileraker/assets/79816358/e2c78741-8060-4d0a-8cae-154873f914fc)
![Screenshot 2023-06-14 at 6 07 51 PM](https://github.com/Clon1998/mobileraker/assets/79816358/ba0ae6ad-41be-48bf-8d26-997b6e026d41)

**Desktop (please complete the following information):**
 n/a

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 16.5

**Mobileraker-Version
2.3.5-181

**Additional context**
This error occurs when the printer is set up with and without OctoEverywhere

**Comment by davidebrock** [comment]
Decided to work suddenly with no explained reason or extra work.
