### ISSUE TITLE
Failed-Key: bed_mesh "default"

### ISSUE THREAD

**Issue by kiinami** [Clon1998/mobileraker#427]
### Description
Connecting the printer gives error on loading the dashboard. Console and other sections work correctly.

### Steps to Reproduce
1. Connect the printer
2. Enter the dashboard

### Expected Behavior
Dashboard loads

### Version Information

- Device-OS (Android/iOS): iOS
- Mobileraker: 2.8.1-563

### Debug Logs
Exception:
 NoSuchMethodError: Closure call with mismatched arguments: function 'PrinterBuilder._updateBedMesh'
Receiver: Closure: (Map<String, dynamic>, PrinterBuilder) => PrinterBuilder from Function '_updateBedMesh@855022109': static.
Tried calling: PrinterBuilder._updateBedMesh("\"default\"", _Map len:0, Instance of 'PrinterBuilder')
Found: PrinterBuilder._updateBedMesh(Map<String, dynamic>, PrinterBuilder) => PrinterBuilder

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:85)
#2      PrinterBuilder.partialUpdateField (package:common/data/dto/machine/printer_builder.dart:219)
#3      PrinterService._parseObjectType (package:common/service/moonraker/printer_service.dart:530)
#4      PrinterService._temperatureStore.<anonymous closure> (package:common/service/moonraker/printer_service.dart:484)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633)
#6      PrinterService._parseQueriedObjects (package:common/service/moonraker/printer_service.dart:545)
#7      PrinterService._printerObjectsQuery (package:common/service/moonraker/printer_service.dart:569)
<asynchronous suspension>
#8      PrinterService.refreshPrinter (package:common/service/moonraker/printer_service.dart:172)
<asynchronous suspension>

Failed-Key: bed_mesh "default" 
Raw JSON:
```json
{
    "bed_mesh": {
        "mesh_matrix": [
            [
                0.361349,
                0.246143,
                0.165415,
                0.108849,
                0.067822,
                0.035402,
                0.006349,
                -0.022888,
                -0.054165,
                -0.087651,
                -0.12182,
                -0.153456,
                -0.177651
            ],
            [
                0.256462,
                0.235537,
                0.203057,
                0.166339,
                0.130803,
                0.09997,
                0.075462,
                0.057004,
                0.042422,
                0.027643,
                0.006696,
                -0.028288,
                -0.087077
            ],
            [
                0.170981,
                0.185252,
                0.175019,
                0.152234,
                0.126052,
                0.102829,
                0.086123,
                0.076691,
                0.072494,
                0.068693,
                0.057649,
                0.028928,
                -0.030707
            ],
            [
                0.102349,
                0.117042,
                0.113129,
                0.099849,
                0.084252,
                0.071197,
                0.063349,
                0.061184,
                0.062987,
                0.064849,
                0.060672,
                0.042166,
                -0.001151
            ],
            [
                0.047968,
                0.047519,
                0.041992,
                0.035012,
                0.029199,
                0.026171,
                0.026542,
                0.029925,
                0.034928,
                0.039156,
                0.039211,
                0.030694,
                0.008201
            ],
            [
                0.005197,
                -0.011852,
                -0.021011,
                -0.023939,
                -0.022202,
                -0.017268,
                -0.010513,
                -0.003218,
                0.003433,
                0.008347,
                0.010529,
                0.009076,
                0.003182
            ],
            [
                -0.028651,
                -0.054744,
                -0.065719,
                -0.066151,
                -0.059929,
                -0.050256,
                -0.039651,
                -0.029947,
                -0.022293,
                -0.017151,
                -0.014299,
                -0.01283,
                -0.011151
            ],
            [
                -0.056303,
                -0.079975,
                -0.089197,
                -0.08826,
                -0.080851,
                -0.070047,
                -0.058322,
                -0.047538,
                -0.038955,
                -0.033221,
                -0.030381,
                -0.029871,
                -0.030521
            ],
            [
                -0.080532,
                -0.091509,
                -0.095731,
                -0.09439,
                -0.088723,
                -0.080014,
                -0.069593,
                -0.058837,
                -0.049168,
                -0.042054,
                -0.039011,
                -0.0416,
                -0.051429
            ],
            [
                -0.104151,
                -0.098447,
                -0.09683,
                -0.096151,
                -0.094188,
                -0.089645,
                -0.082151,
                -0.072262,
                -0.06146,
                -0.052151,
                -0.04767,
                -0.052274,
                -0.071151
            ],
            [
                -0.130019,
                -0.115039,
                -0.111227,
                -0.112643,
                -0.114777,
                -0.114546,
                -0.110297,
                -0.101803,
                -0.090267,
                -0.07832,
                -0.07002,
                -0.070856,
                -0.087744
            ],
            [
                -0.161038,
                -0.160674,
                -0.164875,
                -0.170451,
                -0.174908,
                -0.176443,
                -0.173951,
                -0.167022,
                -0.155938,
                -0.141678,
                -0.125914,
                -0.111014,
                -0.10004
            ],
            [
                -0.200151,
                -0.259886,
                -0.290953,
                -0.303651,
                -0.305886,
                -0.303176,
                -0.298651,
                -0.293052,
                -0.284731,
                -0.269651,
                -0.241386,
                -0.19112,
                -0.107651
            ]
        ],
        "mesh_max": [
            240,
            235
        ],
        "mesh_min": [
            15,
            15
        ],
        "probed_matrix": [
            [
                0.361349,
                0.108849,
                0.006349,
                -0.087651,
                -0.177651
            ],
            [
                0.102349,
                0.099849,
                0.063349,
                0.064849,
                -0.001151
            ],
            [
                -0.028651,
                -0.066151,
                -0.039651,
                -0.017151,
                -0.011151
            ],
            [
                -0.104151,
                -0.096151,
                -0.082151,
                -0.052151,
                -0.071151
            ],
            [
                -0.200151,
                -0.303651,
                -0.298651,
                -0.269651,
                -0.107651
            ]
        ],
        "profile_name": "default",
        "profiles": {
            "default": {
                "mesh_params": {
                    "algo": "lagrange",
                    "max_x": 240,
                    "max_y": 235,
                    "mesh_x_pps": 2,
                    "mesh_y_pps": 2,
                    "min_x": 15,
                    "min_y": 15,
                    "tension": 0.2,
                    "x_count": 5,
                    "y_count": 5
                },
                "points": [
                    [
                        0.361349,
                        0.108849,
                        0.006349,
                        -0.087651,
                        -0.177651
                    ],
                    [
                        0.102349,
                        0.099849,
                        0.063349,
                        0.064849,
                        -0.001151
                    ],
                    [
                        -0.028651,
                        -0.066151,
                        -0.039651,
                        -0.017151,
                        -0.011151
                    ],
                    [
                        -0.104151,
                        -0.096151,
                        -0.082151,
                        -0.052151,
                        -0.071151
                    ],
                    [
                        -0.200151,
                        -0.303651,
                        -0.298651,
                        -0.269651,
                        -0.107651
                    ]
                ]
            }
        }
    },
    "bed_mesh \"default\"": {},
    "configfile": {
        "config": {
            "bed_mesh": {},
            "bed_mesh default": {},
            "buttons": {},
            "controller_fan controller_fan": {},
            "cs1237": {},
            "display_status": {},
            "exclude_object": {},
            "extruder": {},
            "fan": {},
            "filament_hub": {},
            "gcode_arcs": {},
            "gcode_macro M486": {},
            "gcode_macro M555": {},
            "gcode_macro MOVE_HEAT_POS": {},
            "gcode_macro SET_SPOOL": {},
            "gcode_macro SINGLE_WIPE_NOZZLE": {},
            "gcode_macro UNDERLINE": {},
            "gcode_macro WIPE_NOZZLE": {},
            "heater_bed": {},
            "heater_fan extruder_fan": {},
            "input_shaper": {},
            "led_pin": {},
            "leviQ3": {},
            "lis2dw12": {},
            "lis2dw12 bed": {},
            "mcu": {},
            "mcu nozzle_mcu": {},
            "motion_report": {},
            "ota_filament_hub": {},
            "pause_resume": {},
            "pid_calibrate": {},
            "printer": {},
            "printer_marco": {},
            "probe": {},
            "resonance_tester": {},
            "respond": {},
            "safe_z_home": {},
            "stepper_x": {},
            "stepper_y": {},
            "stepper_z": {},
            "timelapse": {},
            "tmc2209 extruder": {},
            "tmc2209 stepper_x": {},
            "tmc2209 stepper_y": {},
            "tmc2209 stepper_z": {},
            "verify_heater extruder": {},
            "verify_heater heater_bed": {},
            "virtual_sdcard": {}
        },
        "save_config_pending": false,
        "save_config_pending_items": {},
        "settings": {
            "bed_mesh": {
                "algorithm": "lagrange",
                "bicubic_tension": 0.2,
                "fade_end": 0,
                "fade_start": 0,
                "horizontal_move_z": 4,
                "mesh_radius": 0,
                "move_check_distance": 5,
                "speed": 120,
                "split_delta_z": 0.0125
            },
            "bed_mesh default": {
                "algo": "lagrange",
                "max_x": 240,
                "max_y": 235,
                "min_x": 15,
                "min_y": 15,
                "tension": 0.2
            },
            "controller_fan controller_fan": {
                "cycle_time": 0.01,
                "fan_speed": 1,
                "heater": [
                    "extruder"
                ],
                "idle_speed": 1,
                "idle_timeout": 30,
                "kick_start_time": 0.01,
                "max_power": 1,
                "off_below": 0,
                "pin": "PB0",
                "shutdown_speed": 0,
                "stepper": []
            },
            "cs1237": {
                "dout_pin": "nozzle_mcu:PA6",
                "sclk_pin": "nozzle_mcu:PA5"
            },
            "extruder": {
                "control": "pid",
                "dir_pin": "nozzle_mcu:PC15",
                "enable_pin": "!nozzle_mcu:PC13",
                "filament_diameter": 1.75,
                "gear_ratio": [],
                "heater_pin": "nozzle_mcu:PB8",
                "inline_resistor": 0,
                "instantaneous_corner_velocity": 1,
                "max_extrude_cross_section": 50,
                "max_extrude_only_accel": 5321.6216073828855,
                "max_extrude_only_distance": 100,
                "max_extrude_only_velocity": 159.64864822148658,
                "max_power": 1,
                "max_safe_temp": 300,
                "max_temp": 320,
                "min_extrude_temp": 170,
                "min_safe_temp": 170,
                "min_temp": -200,
                "nozzle_diameter": 0.4,
                "pid_kd": 72.016108,
                "pid_ki": 0.517208,
                "pid_kp": 12.20612,
                "pressure_advance": 0.02,
                "pressure_advance_smooth_time": 0.04,
                "pullup_resistor": 4700,
                "pwm_cycle_time": 0.1,
                "rotation_distance": 6.426,
                "sensor_pin": "nozzle_mcu:PA0",
                "sensor_type": "NTC 100K MGB18-104F39050L32",
                "smooth_time": 1,
                "step_pin": "nozzle_mcu:PC14"
            },
            "fan": {
                "cycle_time": 0.002,
                "kick_start_time": 0.01,
                "max_power": 1,
                "off_below": 0,
                "pin": "nozzle_mcu:PB5",
                "shutdown_speed": 0
            },
            "filament_hub": {
                "action_timeout": 240,
                "config_file": "/userdata/app/gk/config/ams_config.cfg",
                "config_path": "/userdata/app/gk/config/",
                "cruising_speed": 200,
                "cutter_pin": "nozzle_mcu:PB1",
                "cutter_position": -15,
                "default_feed_speed": 25,
                "default_unwind_speed": 15,
                "delay_before_throw": 3,
                "filament_calibrate": 0,
                "flush_multiplier": 1,
                "impact_position": 0,
                "impact_speed": 10,
                "pre_sweep_position": 278,
                "serial": "",
                "serial1": "",
                "serial_prefix": "usb-ANYCUBIC_ACE",
                "sweep_fan_speed": 0,
                "sweep_position": 271.5,
                "sweep_speed": 5,
                "switch_pin": "nozzle_mcu:PB0",
                "throw_position": 250,
                "unwind_length_after_triggered": 90
            },
            "force_move": {
                "enable_force_move": false
            },
            "gcode_arcs": {
                "resolution": 1
            },
            "gcode_macro m486": {
                "description": "G-Code macro",
                "gcode": "{% if \"T\" in params %}\nEXCLUDE_OBJECT RESET=1\nEXCLUDE_OBJECT_SET_OBJ T={{ params.T }}\n{% endif %}\n{% if params.C %}\nEXCLUDE_OBJECT CURRENT=1\n{% endif %}\n{% if params.P %}\nEXCLUDE_OBJECT NAME={{ params.P }}\n{% endif %}\n{% if params.S %}\n{% if params.S == \"-1\" %}\nEXCLUDE_OBJECT_END_NO_OBJ\n{% else %}\nEXCLUDE_OBJECT_START NAME={{ params.S }}\n{% endif %}\n{% endif %}\n{% if params.U %}\nEXCLUDE_OBJECT RESET=1 NAME={{ params.U }}\n{% endif %}"
            },
            "gcode_macro m555": {
                "description": "G-Code macro",
                "gcode": "SET_SPOOL SPOOL_ID={{ params.S }}"
            },
            "gcode_macro move_heat_pos": {
                "description": "G-Code macro",
                "gcode": "G90\nG1 Z15 F4800\nHOME_XY"
            },
            "gcode_macro set_spool": {
                "description": "G-Code macro",
                "gcode": "{{ action_call_remote_method(\"spoolman_set_active_spool\", params) }}"
            },
            "gcode_macro single_wipe_nozzle": {
                "description": "G-Code macro",
                "gcode": "G90\nG1 X46 Y260 Z-0.8 F9600\nG1 X50 Y260 Z1 F9600\nG1 X86 Y260 Z1 F9600\nG1 X90 Y260 Z-0.8 F9600\nG1 X90 Y259 Z-0.8 F9600\nG1 X86 Y259 Z1 F9600\nG1 X50 Y259 Z1 F9600\nG1 X46 Y259 Z-0.8 F9600"
            },
            "gcode_macro underline": {
                "description": "G-Code macro",
                "gcode": "G90\nG1 Z0.28\nG92 E0\nG1 Y1 F2400\nG1 X180 E40 F500\nG92 E0\nG1 E-0.5 F300"
            },
            "gcode_macro wipe_nozzle": {
                "description": "G-Code macro",
                "gcode": "single_wipe_nozzle\nsingle_wipe_nozzle\nsingle_wipe_nozzle\nG1 X46 Y259 Z1 F9600\nG1 X46 Y259.5 Z-0.8 F9600"
            },
            "heater_bed": {
                "control": "pid",
                "heater_pin": "PA0",
                "inline_resistor": 0,
                "max_power": 1,
                "max_safe_temp": 110,
                "max_temp": 120,
                "min_extrude_temp": 170,
                "min_safe_temp": 45,
                "min_temp": -200,
                "pid_kd": 248.182,
                "pid_ki": 0.77,
                "pid_kp": 54.027,
                "pullup_resistor": 4700,
                "pwm_cycle_time": 0.1,
                "sensor_pin": "PC0",
                "sensor_type": "NTC 100K beta 3950",
                "smooth_time": 1
            },
            "heater_fan extruder_fan": {
                "cycle_time": 0.01,
                "fan_speed": 1,
                "heater": [
                    "extruder"
                ],
                "heater_temp": 50,
                "kick_start_time": 0.01,
                "max_power": 1,
                "off_below": 0,
                "pin": "nozzle_mcu:PB6",
                "shutdown_speed": 0
            },
            "input_shaper": {
                "damping_ratio_x": 0.1,
                "damping_ratio_y": 0.1,
                "shaper_freq_x": 58.6,
                "shaper_freq_y": 71,
                "shaper_type": "mzv",
                "shaper_type_x": "mzv",
                "shaper_type_y": "2hump_ei"
            },
            "led_pin": {
                "pin1": "nozzle_mcu:PB9",
                "pin2": "!nozzle_mcu:PA15"
            },
            "leviq3": {
                "bed_temp": 60,
                "expansion_factor": 0.0375,
                "extru_end_temp": 140,
                "extru_in": 35,
                "extru_in_speed": 30,
                "extru_out": 25,
                "extru_out_speed": 3,
                "extru_temp": 170,
                "homing_retry_count": 10,
                "max_diff": 5000,
                "noise_diff": 2500,
                "rough_platform_offset": [
                    60,
                    258,
                    0.2
                ],
                "to_z_up_speed": 15,
                "to_zero_speed": 200,
                "z_up": 3
            },
            "lis2dw12": {
                "cs_pin": "nozzle_mcu:PB12",
                "spi_software_miso_pin": "nozzle_mcu:PB14",
                "spi_software_mosi_pin": "nozzle_mcu:PB15",
                "spi_software_sclk_pin": "nozzle_mcu:PB13"
            },
            "lis2dw12 bed": {
                "cs_pin": "PA15",
                "spi_software_miso_pin": "PC11",
                "spi_software_mosi_pin": "PC12",
                "spi_software_sclk_pin": "PC10"
            },
            "mcu": {
                "max_stepper_error": 0.000025,
                "restart_method": "command",
                "serial": "/dev/ttyS3"
            },
            "mcu nozzle_mcu": {
                "max_stepper_error": 0.000025,
                "restart_method": "command",
                "serial": "/dev/ttyS0"
            },
            "pause_resume": {
                "extru_load": 50,
                "extru_pull": 2,
                "extru_unload": 2,
                "recover_velocity": 50,
                "z_up": 10
            },
            "pid_calibrate": {
                "move_z_up": 5
            },
            "printer": {
                "buffer_time_high": 2,
                "buffer_time_low": 1,
                "buffer_time_start": 0.25,
                "kinematics": "cartesian",
                "max_accel": 20000,
                "max_accel_to_decel": 20000,
                "max_velocity": 600,
                "max_z_accel": 3000,
                "max_z_velocity": 20,
                "move_flush_time": 0.05,
                "square_corner_velocity": 5,
                "velocity_range_limit": "",
                "velocity_range_limit_begin_min": 20,
                "velocity_range_limit_hit_log": "0"
            },
            "probe": {
                "final_speed": 3.4,
                "lift_speed": 5.8,
                "pin": "PB15",
                "samples_result": "weighted",
                "speed": 3.5,
                "x_offset": 0,
                "y_offset": 0,
                "z_gap": 0.01,
                "z_gap_left_down_count": 30,
                "z_gap_left_up_count": 30,
                "z_gap_limt": 0.03,
                "z_offset": -0.1828
            },
            "resonance_tester": {
                "accel_chip_x": "lis2dw12",
                "accel_chip_y": "lis2dw12 bed",
                "accel_per_hz": 75,
                "hz_per_sec": 1,
                "max_accel": 10000,
                "max_freq": 133.33333333333334,
                "min_freq": 5,
                "mm_sec": 1,
                "move_speed": 50,
                "test_freq_end": 133.33333333333334,
                "test_freq_start": 5
            },
            "safe_z_home": {
                "speed": 200,
                "z_hop": 15,
                "z_hop_speed": 8
            },
            "safe_z_home default": {
                "home_x_pos": 0
            },
            "stepper_x": {
                "dir_pin": "PA4",
                "enable_pin": "!PC3",
                "gear_ratio": [],
                "rotation_distance": 32,
                "step_pin": "PA5"
            },
            "stepper_y": {
                "dir_pin": "!PA7",
                "enable_pin": "!PC3",
                "gear_ratio": [],
                "rotation_distance": 32,
                "step_pin": "PC4"
            },
            "stepper_z": {
                "dir_pin": "PB1",
                "enable_pin": "!PC3",
                "gear_ratio": [],
                "rotation_distance": 8,
                "step_pin": "PC9"
            },
            "timelapse": {
                "snap_x_pos": 278,
                "snap_y_pos": 200
            },
            "tmc2209 extruder": {
                "driver_dedge": true,
                "driver_hend": 0,
                "driver_hstrt": 5,
                "driver_iholddelay": 8,
                "driver_multistep_filt": true,
                "driver_pwm_autograd": true,
                "driver_pwm_autoscale": true,
                "driver_pwm_freq": 1,
                "driver_pwm_grad": 14,
                "driver_pwm_lim": 12,
                "driver_pwm_ofs": 36,
                "driver_pwm_reg": 8,
                "driver_sgthrs": 0,
                "driver_tbl": 2,
                "driver_toff": 3,
                "driver_tpowerdown": 20,
                "driver_vsense": false,
                "hold_current": 2.4,
                "run_current": 0.8,
                "sense_resistor": 0.075,
                "stealthchop_threshold": 99999,
                "uart_pin": "nozzle_mcu:PA3"
            },
            "tmc2209 stepper_x": {
                "diag_pin": "PA6",
                "driver_dedge": true,
                "driver_hend": 0,
                "driver_hstrt": 5,
                "driver_iholddelay": 8,
                "driver_multistep_filt": true,
                "driver_pwm_autograd": true,
                "driver_pwm_autoscale": true,
                "driver_pwm_freq": 1,
                "driver_pwm_grad": 14,
                "driver_pwm_lim": 12,
                "driver_pwm_ofs": 36,
                "driver_pwm_reg": 8,
                "driver_tbl": 2,
                "driver_toff": 3,
                "driver_tpowerdown": 20,
                "driver_vsense": false,
                "hold_current": 2.4,
                "run_current": 1.5,
                "sense_resistor": 0.075,
                "stealthchop_threshold": 0,
                "uart_pin": "PA3"
            },
            "tmc2209 stepper_y": {
                "diag_pin": "PC5",
                "driver_dedge": true,
                "driver_hend": 0,
                "driver_hstrt": 5,
                "driver_iholddelay": 8,
                "driver_multistep_filt": true,
                "driver_pwm_autograd": true,
                "driver_pwm_autoscale": true,
                "driver_pwm_freq": 1,
                "driver_pwm_grad": 14,
                "driver_pwm_lim": 12,
                "driver_pwm_ofs": 36,
                "driver_pwm_reg": 8,
                "driver_tbl": 2,
                "driver_toff": 3,
                "driver_tpowerdown": 20,
                "driver_vsense": false,
                "hold_current": 2.4,
                "run_current": 1.7,
                "sense_resistor": 0.075,
                "stealthchop_threshold": 0,
                "uart_pin": "PA3"
            },
            "tmc2209 stepper_z": {
                "driver_dedge": true,
                "driver_hend": 0,
                "driver_hstrt": 5,
                "driver_iholddelay": 8,
                "driver_pwm_autograd": true,
                "driver_pwm_autoscale": true,
                "driver_pwm_freq": 1,
                "driver_pwm_grad": 14,
                "driver_pwm_lim": 12,
                "driver_pwm_ofs": 36,
                "driver_pwm_reg": 8,
                "driver_sgthrs": 0,
                "driver_tbl": 2,
                "driver_toff": 3,
                "driver_tpowerdown": 20,
                "driver_vsense": false,
                "hold_current": 2.4,
                "run_current": 1.4,
                "sense_resistor": 0.075,
                "stealthchop_threshold": 99999,
                "uart_pin": "PA3"
            },
            "verify_heater extruder": {
                "check_gain_time": 30,
                "heating_gain": 1,
                "hysteresis": 5,
                "max_error": 120
            },
            "verify_heater heater_bed": {
                "check_gain_time": 300,
                "heating_gain": 1,
                "hysteresis": 5,
                "max_error": 120
            },
            "virtual_sdcard": {
                "on_error_gcode": ""
            }
        },
        "warnings": []
    },
    "display_status": {},
    "extruder": {
        "can_extrude": false,
        "power": 0,
        "pressure_advance": 0.02,
        "smooth_time": 0.04,
        "target": 0,
        "temperature": 63
    },
    "fan": {
        "rpm": 0,
        "speed": 0
    },
    "gcode_macro cancel_print": {},
    "gcode_macro pause": {},
    "gcode_macro resume": {},
    "gcode_move": {
        "absolute_coordinates": true,
        "absolute_extrude": true,
        "extrude_factor": 1,
        "gcode_position": [
            0,
            0,
            -0.361349,
            0
        ],
        "homing_origin": [
            0,
            0,
            0,
            0
        ],
        "position": [
            0,
            0,
            -0.361349,
            0
        ],
        "speed": 1500,
        "speed_factor": 1,
        "speed_mode": 1
    },
    "heater_bed": {
        "power": 0,
        "target": 0,
        "temperature": 45
    },
    "motion_report": {},
    "print_stats": {
        "filament_used": 0,
        "filename": "",
        "info": {
            "current_layer": 0,
            "total_layer": 0
        },
        "message": "",
        "print_duration": 0,
        "state": "standby",
        "total_duration": 0
    },
    "toolhead": {
        "axis_maximum": [
            278.5,
            260,
            262,
            0
        ],
        "axis_minimum": [
            -19.5,
            -6,
            -4,
            0
        ],
        "extruder": "extruder",
        "homed_axes": "",
        "max_accel": 20000,
        "max_accel_to_decel": 20000,
        "max_velocity": 600,
        "position": [
            0,
            0,
            0,
            0
        ],
        "square_corner_velocity": 5,
        "stalls": 0
    },
    "virtual_sdcard": {
        "bed_temperature": 0,
        "brim_type": "",
        "current_layer": 0,
        "extruder_colour": null,
        "extruder_temperature": 0,
        "filament_retract_length": 0,
        "filament_type": "",
        "filament_used": "",
        "file_path": "/useremain/app/gk/gcodes/",
        "file_position": 0,
        "file_size": 0,
        "fill_density": 0,
        "is_active": false,
        "is_homing": 0,
        "layer_height": 0,
        "model_size_x": 0,
        "model_size_y": 0,
        "model_size_z": 0,
        "perimeter_extrusion_width": 0,
        "perimeter_speed": 0,
        "perimeters": 0,
        "printer_settings_id": "",
        "progress": 0,
        "support_material_auto": 0,
        "timelapse_type": 0,
        "total_layer": 0,
        "total_time": 0,
        "travel_speed": 0
    }
}
```

### Additional Context
The printer is an Anycubic Kobra 3 running custom firmware (https://github.com/utkabobr/DuckPro-Kobra3 and https://github.com/utkabobr/moonraker/tree/duckpro) to enable mobileraker on the heavily modified klipper implementation it has. 

**The error obviously is not the fault of mobileraker but rather of the modified moonraker implementation, so what I would like to know is that is wrong with the JSON it sends so that I can fix it on the CFW side.**

---

#### Checklist
To help us diagnose the issue, please ensure you've completed the following steps:
- [x] Provided a clear bug description.
- [x] Listed detailed steps to reproduce the issue.
- [x] Described the expected behavior.
- [x] Included the Mobileraker version you are using.

**Comment by Clon1998** [comment]
Thanks for reporting the issue.

First time seeing that. I'll have a look during the weekend.

**Comment by kiinami** [comment]
> The error obviously is not the fault of mobileraker but rather of the modified moonraker implementation, so what I would like to know is that is wrong with the JSON it sends so that I can fix it on the CFW side.

Please note this

**Comment by Clon1998** [comment]
Hey,
so your json contains `"bed_mesh \"default\"": {},` which is causing the issue.
Default Klipper only allows a single `bed_mesh` to be configured; however, your setup allows multiple, which causes an issue with mobileraker's auto-mapping function as it tries to call the `_updateBedMesh` method with the identifier `default,` which is not supported.
